"""v102d-fix — upstream-API quota monitor + subscriber notifications.

Owner-asked: when the upstream APIs (Open-Meteo for weather, Deye Cloud
for inverter telemetry) approach their daily call ceiling, every
subscriber should see a calm "approaching limit" notification, and a
firm "limit reached" notification when the cap is hit. The Smart
Decision card already surfaces the cause inline — this module is what
puts the proactive heads-up in the Notification Center.

Design
------
* **Counters** live in-process in a module-level dict keyed by
  ``(api_name, YYYY-MM-DD)``. Resets implicitly when the date key
  rolls over (daily reset == new key). Resetting on app restart is
  acceptable: the upstream provider's clock-of-day reset is what
  matters; our counter only needs to be honest *during* the day.

* **Thresholds**: 80% → ``api_quota_warning`` (warn), 100% →
  ``api_quota_exhausted`` (critical). Both fire **once per day per API
  per subscriber** — dedup is enforced by querying ``NotificationEvent``
  for an existing row with the same ``event_type`` + an in-payload
  ``threshold_key`` that already encodes the date and percent.

* **Recipients**: every non-admin ``AppUser.is_active``. Open-Meteo +
  Deye are shared resources — when they're exhausted the impact is
  universal, so every subscriber deserves to know why their charts /
  insights / decisions are showing degraded copy.

* **Hooks**: callers wrap their HTTP success / failure paths in
  ``record_call(api_name, success=True|False, exhausted=False|True)``.
  ``exhausted=True`` short-circuits the counter past 100% so a hard
  upstream-rejection (e.g. Open-Meteo HTTP 429) immediately fires the
  100% notification regardless of the locally-tracked count. This
  matters because our local counter is blind to traffic generated by
  *other* clients on the same API key (Deye especially — the same key
  may serve the web dashboard + CLI tools).

* **Limits**: per-API, configurable via ``current_app.config``
  (``OPEN_METEO_DAILY_LIMIT`` / ``DEYE_DAILY_LIMIT``) with sensible
  defaults from each provider's published plan. Admins can tune
  without redeploying by setting them in the running config.
"""

from __future__ import annotations

import json
import logging
from datetime import date, datetime
from threading import Lock
from typing import Optional

from flask import current_app, has_app_context

from ..extensions import db
from ..models import AppUser, NotificationEvent

log = logging.getLogger(__name__)


# ── Config defaults ───────────────────────────────────────────────────

API_OPEN_METEO = 'open_meteo'
API_DEYE = 'deye'

# Provider-published daily ceilings. Open-Meteo's free tier allows
# 10000 calls/day per IP; Deye's developer plan grants 1000 calls/day
# per app key on the standard tier. Both are overridable via config.
_DEFAULT_LIMITS: dict[str, int] = {
    API_OPEN_METEO: 10000,
    API_DEYE: 1000,
}

# Two thresholds. Crossing each fires one notification per subscriber
# per day per api (dedup via threshold_key in NotificationEvent.result).
THRESHOLD_WARNING = 0.80
THRESHOLD_CRITICAL = 1.00

# Arabic labels used in the user-facing notification copy.
_API_LABELS_AR = {
    API_OPEN_METEO: 'مزوّد الطقس',
    API_DEYE: 'مزوّد بيانات الإنفرتر',
}

# In-process counter keyed by (api_name, YYYY-MM-DD) → int.
_counter_lock = Lock()
_counters: dict[tuple[str, str], int] = {}
# Tracks which (api, date, level) tuples have already been notified
# so we don't re-emit a per-subscriber notification while the counter
# keeps climbing past the threshold. The DB dedup is the
# source-of-truth — this in-memory set is just a fast-path skip.
_notified: set[tuple[str, str, str]] = set()


# ── Public surface ────────────────────────────────────────────────────


def daily_limit(api_name: str) -> int:
    """Resolve the daily-call ceiling for ``api_name``. Reads
    ``OPEN_METEO_DAILY_LIMIT`` / ``DEYE_DAILY_LIMIT`` from
    ``current_app.config`` when an app context is active; otherwise
    falls back to the published-plan default.
    """
    key = {
        API_OPEN_METEO: 'OPEN_METEO_DAILY_LIMIT',
        API_DEYE: 'DEYE_DAILY_LIMIT',
    }.get(api_name)
    if key and has_app_context():
        try:
            value = int(current_app.config.get(key, 0) or 0)
            if value > 0:
                return value
        except Exception:
            pass
    return _DEFAULT_LIMITS.get(api_name, 0)


def get_usage(api_name: str) -> dict:
    """Return ``{used, limit, percent}`` for the current local day."""
    today = date.today().isoformat()
    with _counter_lock:
        used = _counters.get((api_name, today), 0)
    limit = daily_limit(api_name)
    percent = (used / limit) if limit > 0 else 0.0
    return {'used': used, 'limit': limit, 'percent': percent}


def record_call(
    api_name: str,
    *,
    success: bool = True,
    exhausted: bool = False,
) -> None:
    """Record one upstream API call.

    Parameters
    ----------
    api_name
        ``API_OPEN_METEO`` or ``API_DEYE``.
    success
        Whether the call returned data. Failures still tick the
        counter — the upstream provider counts attempts regardless of
        whether we used the response.
    exhausted
        Force the counter to the 100% mark for today. Use this when
        the upstream returned a hard rate-limit error (HTTP 429,
        Deye-specific quota error code, etc.) — even if our local
        counter is below the limit, the provider has clearly told us
        we're done for the day.

    The function is intentionally swallow-everything. A bookkeeping
    failure must never break a real upstream call.
    """
    try:
        today = date.today().isoformat()
        key = (api_name, today)
        with _counter_lock:
            current = _counters.get(key, 0)
            new_value = current + 1
            if exhausted:
                limit = daily_limit(api_name)
                if limit > 0:
                    new_value = max(new_value, limit)
            _counters[key] = new_value
        # Threshold check is done outside the counter lock so we don't
        # hold it across a DB write.
        _check_thresholds(api_name)
    except Exception as exc:  # pragma: no cover - defensive
        log.warning('api_quota_monitor.record_call failed: %s', exc)


def reset_for_test(api_name: Optional[str] = None) -> None:
    """Test helper — clear counters + dedup set. Not for production."""
    with _counter_lock:
        if api_name is None:
            _counters.clear()
            _notified.clear()
        else:
            today = date.today().isoformat()
            _counters.pop((api_name, today), None)
            _notified.discard((api_name, today, 'warning'))
            _notified.discard((api_name, today, 'critical'))


# ── Threshold detection + notification ────────────────────────────────


def _check_thresholds(api_name: str) -> None:
    if not has_app_context():
        return
    state = get_usage(api_name)
    limit = state['limit']
    if limit <= 0:
        return
    today = date.today().isoformat()
    percent = state['percent']
    used = state['used']

    if percent >= THRESHOLD_CRITICAL:
        level = 'critical'
    elif percent >= THRESHOLD_WARNING:
        level = 'warning'
    else:
        return

    fast_skip_key = (api_name, today, level)
    if fast_skip_key in _notified:
        return

    try:
        _emit_threshold_notifications(
            api_name=api_name,
            level=level,
            used=used,
            limit=limit,
            percent=percent,
            today=today,
        )
        _notified.add(fast_skip_key)
    except Exception as exc:  # pragma: no cover - defensive
        log.warning(
            'api_quota_monitor: failed to emit threshold notifications '
            '(api=%s level=%s): %s',
            api_name, level, exc,
        )


def _threshold_key(api_name: str, today: str, level: str) -> str:
    """Stable key embedded in NotificationEvent.result so the DB-side
    dedup query can spot an existing notification for this exact
    (api, day, level) tuple.
    """
    return f'api_quota:{api_name}:{today}:{level}'


def _emit_threshold_notifications(
    *,
    api_name: str,
    level: str,
    used: int,
    limit: int,
    percent: float,
    today: str,
) -> None:
    label = _API_LABELS_AR.get(api_name, api_name)
    threshold_key = _threshold_key(api_name, today, level)
    event_type = 'api_quota_exhausted' if level == 'critical' else 'api_quota_warning'

    if level == 'critical':
        title = f'تم بلوغ حصة استدعاءات {label}'
        message = (
            f'بلغ النظام {used} من {limit} استدعاء لـ{label} اليوم. '
            'بعض القرارات والرسوم البيانية قد لا تتحدّث حتى تجدّد الحصة '
            'مع منتصف الليل.'
        )
        status = 'critical'
    else:
        pct_int = int(round(percent * 100))
        title = f'اقتراب بلوغ حصة استدعاءات {label}'
        message = (
            f'استُهلكت {pct_int}% من حصة {label} اليوم ({used} من {limit}). '
            'سيُكتفى بالقراءات المخزّنة لو تم بلوغ الحد، حتى تجدّد الحصة '
            'منتصف الليل.'
        )
        status = 'warning'

    payload_json = json.dumps(
        {
            'threshold_key': threshold_key,
            'api': api_name,
            'level': level,
            'used': used,
            'limit': limit,
            'percent': round(percent, 4),
        },
        ensure_ascii=False,
    )

    # Per-subscriber dedup: if a notification with the same
    # threshold_key already exists for any user today, the sweep
    # already ran. We still iterate to cover NEW subscribers added
    # mid-day, but skip any user that already has it.
    try:
        users = (
            AppUser.query
            .filter(AppUser.is_active.is_(True))
            .filter((AppUser.is_admin.is_(False)) | (AppUser.is_admin.is_(None)))
            .all()
        )
    except Exception:
        users = []
    # Add admins too — they want to know about the upstream issue.
    try:
        admins = (
            AppUser.query
            .filter(AppUser.is_active.is_(True))
            .filter(AppUser.is_admin.is_(True))
            .all()
        )
    except Exception:
        admins = []

    recipients = list({u.id: u for u in (users + admins)}.values())
    if not recipients:
        return

    rows_created = 0
    now = datetime.utcnow()
    for owner in recipients:
        # Skip if this user already has a notification for the same
        # (api, day, level). Cheap query against a small per-user index.
        try:
            already = (
                NotificationEvent.query
                .filter_by(target_user_id=owner.id, event_type=event_type)
                .filter(NotificationEvent.result.like(f'%{threshold_key}%'))
                .first()
            )
            if already is not None:
                continue
        except Exception:
            # If the dedup query itself fails, prefer NOT inserting to
            # avoid spamming on retry.
            continue
        try:
            row = NotificationEvent(
                event_type=event_type,
                target_user_id=owner.id,
                tenant_id=getattr(owner, 'tenant_id', None),
                source_type='system',
                source_id=None,
                title=title[:220],
                message=message,
                status=status,
                result=payload_json,
                is_read=False,
                appeared_in_bell=False,
                delivered_to_user=False,
                created_at=now,
            )
            db.session.add(row)
            rows_created += 1
        except Exception as exc:  # pragma: no cover - defensive
            log.warning(
                'api_quota_monitor: failed to insert notification for '
                'user_id=%s api=%s level=%s: %s',
                owner.id, api_name, level, exc,
            )
    if rows_created:
        try:
            db.session.commit()
            log.info(
                'api_quota_monitor: emitted %s "%s" notifications '
                '(api=%s used=%s/%s)',
                rows_created, event_type, api_name, used, limit,
            )
        except Exception as exc:
            log.warning(
                'api_quota_monitor: commit failed (api=%s level=%s): %s',
                api_name, level, exc,
            )
            try:
                db.session.rollback()
            except Exception:
                pass


__all__ = [
    'API_OPEN_METEO',
    'API_DEYE',
    'THRESHOLD_WARNING',
    'THRESHOLD_CRITICAL',
    'daily_limit',
    'get_usage',
    'record_call',
    'reset_for_test',
]
